### ISSUE TITLE
cyclic wisp resevoir drain is fixed at 0.37 dust per second

### ISSUE THREAD

**Issue by kristifristi** [Talia-12/Hexal#14] opened 2022-12-05 05:08 UTC
{
  Locate Sentinel //location of item frame with focus(starts with an empty list)
  Entity Purification
  Gemini Decomposition
  Chronicler's Purification
  Reservoir Reflection
  Reveal
  Integration Distillation
  Chronicler's Gambit
  Numerical Reflection: 20
  Delay Wisp
}
Mind's Reflection
Compass' Purification
Numerical Reflection: 100
Summon Cyclic Wisp

the difference between each reservoir reflection is 0.37

**Comment by Talia-12** [comment] 2023-02-14 03:31
This is the intended behavior, the documentation in the patchouli book was incorrect, thank you for bringing it up; should be fixed now.

**Closed by Talia-12** 2023-02-14 03:31 UTC
